// GENERERAD FIL — kör `python3 scripts/konvertera_skapaeget.py` för att uppdatera.
// Bygger på fliken Rådata i senaste Excel-filen under data/.

export interface SkapaEgetRad {
  id: string | null;
  program: string | null;
  projekttyp: string | null;
  startdatum: string | null;
  slutdatum: string | null;
  projektnamn: string;
  vatnummer: string | null;
  organisationsnamn: string;
  organisationsagande: string | null;
  organisationstyp: string | null;
  partnerroll: string | null;
  stad: string | null;
  nuts3: string | null;
  nuts2: string | null;
  partnerbudget: number | null;
  politisktmal: string | null;
  specifiktmal: string | null;
  projektar: string | null;
  land: string | null;
}

export const ANTAL_RADER = 1196;

export const FALT_VARDEN: Record<string, string[]> = {
  "program": [
    "AURORA",
    "Baltic Sea Region",
    "Central Baltic",
    "Interreg North Sea",
    "Interreg europe",
    "Northern Periphery and Arctic",
    "South Baltic Programme",
    "Sverige-Norge",
    "URBACT IV",
    "Öresund-Kattegat-Skagerrak"
  ],
  "projekttyp": [
    "Feasibility study",
    "Full Application",
    "Regular",
    "Regular project",
    "Small",
    "Small Scale Project",
    "Small-scale project"
  ],
  "organisationsagande": [
    "Other",
    "Private",
    "Public"
  ],
  "organisationstyp": [
    "#N/A",
    "Bodies governed by public law",
    "Business support organisation",
    "EGTC",
    "Education and research institution",
    "Enterprise, except SME",
    "Higher education and research institution",
    "Hospital and medical centre",
    "Infrastructure and (Public organisation) service provider",
    "Interest groups including NGOs",
    "International governmental organisation",
    "Large enterprise",
    "Local public authority",
    "NGO",
    "National public authority",
    "Other",
    "Regional public authority",
    "Sectoral agency",
    "Small or medium-sized enterprise (SME)",
    "national, regional and local authorities"
  ],
  "partnerroll": [
    "AP",
    "LP",
    "PP"
  ],
  "stad": [
    "#N/A",
    "Alvesta",
    "Arlanda",
    "Arvidsjaur",
    "Arvika",
    "Bengtsfors",
    "Berg",
    "Boden",
    "Bollnäs",
    "Borgholm",
    "Borlänge",
    "Borås",
    "Botkyrka",
    "Brantevik",
    "Bromma",
    "Bräcke",
    "Båstad",
    "Domsjö",
    "Eda",
    "Ekerö",
    "Enköping",
    "Eskilstuna",
    "Eslöv",
    "Falkenberg",
    "Falköping",
    "Falun",
    "Filipstad",
    "Färjestaden",
    "Gothenburg",
    "Gysinge",
    "Gällivare",
    "Gävle",
    "Göteborg",
    "Götene",
    "Halmstad",
    "Haparanda",
    "Helsingborg",
    "Huddinge",
    "Hultsfred",
    "Härjedalen",
    "Härnösand",
    "Hässleholm",
    "Höganäs",
    "Jokkmokk",
    "Järna",
    "Jönköping",
    "Jörn",
    "Kalix",
    "Kalmar",
    "Karlshamn",
    "Karlskrona",
    "Karlstad",
    "Katrineholm",
    "Kiruna",
    "Kista",
    "Kristianstad",
    "Kristinehamn",
    "Krokom",
    "Kungsbacka",
    "Kungshamn",
    "Laholm",
    "Landskrona",
    "Lidköping",
    "Linköping",
    "Lomma",
    "Ludvika",
    "Lulea",
    "Luleå",
    "Lund",
    "Lycksele",
    "Lysekil",
    "Läckeby",
    "Länghem",
    "Länsstyrelsen Skåne",
    "Löddeköpinge",
    "Malmö",
    "Malung-Sälen",
    "Mellerud",
    "Mora",
    "Motala",
    "Mölndal",
    "Mörbylånga",
    "N/A",
    "Nacka",
    "Norrköping",
    "Norrtälje",
    "Norsjö",
    "Nyköping",
    "Obbola",
    "Olofström",
    "Osby",
    "Oskarshamn",
    "Pajala",
    "Piteå",
    "Ragunda",
    "Robertsfors",
    "Romakloster",
    "Ronneby",
    "Rättvik",
    "Sigtuna",
    "Simrishamn",
    "Sjöbo",
    "Skara",
    "Skellefteå",
    "Skene",
    "Skillinge",
    "Skivarp",
    "Skurup",
    "Skövde",
    "Sollefteå",
    "Solna",
    "Sotenäs",
    "Stenungsund",
    "Stockholm",
    "Storfors",
    "Storuman",
    "Strömstad",
    "Strömsund",
    "Sundbyberg",
    "Sunderbyn",
    "Sundsvall",
    "Svalöv",
    "Svedala",
    "Svenljunga",
    "Sydkoster",
    "Säffle",
    "Söderhamn",
    "Södertälje",
    "Sölvesborg",
    "Tibro",
    "Tomelilla",
    "Torsby",
    "Tranemo",
    "Trelleborg",
    "Trollhättan",
    "Tyresö",
    "Uddevalla",
    "Umea",
    "Umeå",
    "Uppsala",
    "Varberg",
    "Varberg Municipality",
    "Visby",
    "Vreta Kluster",
    "Vänersborg",
    "Vännäs",
    "Värmdö",
    "Västervik",
    "Västerås",
    "Växjö",
    "Ystad",
    "Ängelholm",
    "Åhus",
    "Åmål",
    "Ånge",
    "Åre",
    "Årjäng",
    "Åsele",
    "Åstorp",
    "Åtvidaberg",
    "Öjebyn",
    "Örebro",
    "Örnsköldsvik",
    "Östersund",
    "Överkalix",
    "Övertorneå"
  ],
  "nuts3": [
    "Blekinge län",
    "Dalarnas län",
    "Gotlands län",
    "Gävleborgs län",
    "Hallands län",
    "Jämtlands län",
    "Jönköpings län",
    "Kalmar län",
    "Kronobergs län",
    "N/A",
    "Norrbottens län",
    "Skåne län",
    "Stockholms län",
    "Södermanlands län",
    "Uppsala län",
    "Värmlands län",
    "Västerbottens län",
    "Västernorrlands län",
    "Västmanlands län",
    "Västra Götalands län",
    "Örebro län",
    "Östergötlands län"
  ],
  "nuts2": [
    "Gotland",
    "Mellersta Norrland",
    "N/A",
    "Norra Mellansverige",
    "Småland med öarna",
    "Småland och Öarna",
    "Småland och öarna",
    "Stockholm",
    "Sydsverige",
    "Västsverige",
    "Östra Mellansverige",
    "Övre Norrland"
  ],
  "politisktmal": [
    "ISO",
    "N/A",
    "PO1",
    "PO2",
    "PO3",
    "PO4",
    "PO5",
    "PO6"
  ],
  "specifiktmal": [
    "ISO6.1",
    "ISO6.6",
    "N/A",
    "RSO1.1",
    "RSO1.2",
    "RSO1.3",
    "RSO1.4",
    "RSO1.5",
    "RSO2.1",
    "RSO2.2",
    "RSO2.3",
    "RSO2.4",
    "RSO2.5",
    "RSO2.6",
    "RSO2.7",
    "RSO2.8",
    "RSO3.1",
    "RSO3.2",
    "RSO4.1",
    "RSO4.2",
    "RSO4.3",
    "RSO4.4",
    "RSO4.5",
    "RSO4.6",
    "RSO5.1",
    "RSO5.2",
    "RSO6.1",
    "RSO6.4"
  ],
  "projektar": [
    "2022",
    "2023",
    "2024",
    "2025",
    "2026"
  ],
  "land": [
    "Sverige"
  ]
};
